### ISSUE TITLE
BooleanFields returning as 1/0 (instead of True/False)

### ISSUE THREAD

**Issue by dwasyl** [ESSolutions/django-mssql-backend#16]
Something I've noticed occurring is that BooleanFields are returning 0/1 instead of False/True. The field definitions haven't changed, and pointing the app at another DB with the same data returns the proper False/True.

Any ideas for better debugging of this?

This may be as simple as bringing this PR over [https://github.com/marcogiusti/django-pyodbc-azure/commit/d6c5c49d1d86aa6bcef6bdd582ee1d94852b6448](https://github.com/marcogiusti/django-pyodbc-azure/commit/d6c5c49d1d86aa6bcef6bdd582ee1d94852b6448)

**Comment by OskarPersson** [comment]
Does #17 solve your problem?

**Comment by dwasyl** [comment]
Been away - #17 seemed to do the trick.
