### ISSUE TITLE
Django 3.0 Support?

### ISSUE THREAD

**Issue by hannylicious** [ESSolutions/django-mssql-backend#18]
Just curious if there is a version of this out there (or plans for this) that will be supporting Django 3.0.

Currently looking to tryout the 3.0 features and since this forked worked with 2.2 I wasn't sure if 3.0 support would be added.

**Comment by OskarPersson** [comment]
Yes there are definitely plans to support Django 3.0. I've created #19 with some initial testing and fixes.

**Comment by hannylicious** [comment]
@OskarPersson great!  I figured there would be plans, excited to see once it gets all squared away and give it a shot.

**Comment by hingston** [comment]
Django 3.0 has been [released now](https://docs.djangoproject.com/en/3.0/releases/3.0/).

**Comment by daybarr** [comment]
#19 has been merged to master and released in [2.6.0](https://github.com/ESSolutions/django-mssql-backend/releases/tag/2.6.0) ([PyPI](https://pypi.org/project/django-mssql-backend/2.6.0)) so I think this issue can be closed now?

**Comment by hannylicious** [comment]
I saw that - I [created a PR](https://github.com/ESSolutions/django-mssql-backend/pull/31) to update the documentation to reflect the changes that it now supports 2.2 & 3.0
