### ISSUE TITLE
GitHub repository's website should point at own PyPI page

### ISSUE THREAD

**Issue by daybarr** [ESSolutions/django-mssql-backend#23]
The "website" for this GitHub repo is still set to be https://pypi.org/project/django-pyodbc-azure/, which means that [the project's front page](https://github.com/ESSolutions/django-mssql-backend) links to it at the top:

![image](https://user-images.githubusercontent.com/140142/69966319-07095900-150e-11ea-9f8a-1ddb4aa256da.png)

You (@OskarPersson ?) should probably edit that to point to https://pypi.org/project/django-mssql-backend/ instead to reduce / avoid confusion.

Thanks for your work on this 👍

**Comment by OskarPersson** [comment]
Fixed! Thanks :)

**Comment by daybarr** [comment]
Swift work. Thank you very much.
