### ISSUE TITLE
Compatibility with django 1.11?

### ISSUE THREAD

**Issue by mrbean-bremen** [ESSolutions/django-mssql-backend#53]
We would like to switch to this fork, as it is actively developed, and also because it has the regex support that was missing in the original repository.
As we still need to support django 1.11 and I couldn't find the information: can you say if the current version is still compatible with django 1.11? And in case it is not, would it be possible to merge the regex support into the 1.11 branch and make a pypi release (I could make a PR if you want - basically a copy of the [original PR](https://github.com/michiya/django-pyodbc-azure/pull/128))? It would be more convenient than patching the released version...

Thanks!

**Comment by OskarPersson** [comment]
I'm not sure if it still works with 1.11, we only test and develop for 2.2+ at the moment since that is what is still supported by Django.

**Comment by mrbean-bremen** [comment]
Ok, thanks!
