### ISSUE TITLE
Invalid usage of the option FIRST in the FETCH statement.

### ISSUE THREAD

**Issue by Kiyalshtin47** [ESSolutions/django-mssql-backend#68]
All of a sudden I recently started having this error occur on any django ORM operation that I use:

`[42000] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Invalid usage of the option FIRST in the FETCH statement. (153) (SQLExecDirectW); [42000] [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)`

This is what the query looks like in the django traceback: 

`QUERY = 'SELECT [Entity].[Audit], [Entity].[Class], [Entity].[FromArrow], [Entity].[FromAssc], [Entity].[ID], [Entity].[Name], [Entity].[SeqNum], [Entity].[Properties], [Entity].[ToArrow], [Entity].[ToAssc], [Entity].[Type], [Entity].[UpdateDate], [Entity].[SAGuid], [Entity].[PropType], [Entity].[ShortProps], [Entity].[Activity], [Entity].[CRID], [Entity].[CRURL], [Entity].[CRROOTURL], [Entity].[Version] FROM [Entity] WHERE [Entity].[ID] = %s FETCH FIRST 21 ROWS ONLY' - PARAMS = (1,)`

This is the line of code that is being executed where the error occurs:

`Entity.objects.using(encyclopedia).get(pk=pk)`

Here is my database connection from settings.py (we are on an internal network, so it authenticates using my built in windows credentials):

```
{
    'ENGINE': 'sql_server.pyodbc',
    'NAME': 'database',
    'HOST': 'server',
    'OPTIONS': {
        'driver': 'ODBC Driver 13 for SQL Server',
    }
} 
```

Here are the details of my application installation and versions: 

```
django-mssql-backend==2.8.1
Django==3.0.7
MS SQL Server Version==14.0.3238.1
```

I've been using this package on these same databases in the past, and I have not seen this issue occur before. This makes me think that its something I must have done, but I can't think of what would be causing it. Any help would be greatly appreciated! Thanks!

**Comment by ecogels** [comment]
On microsoft odbc driver page,they say that driver odbc 13 only supports SQL server up to 2016 (preview) and it looks like you are using SQL server 14 = 2017. I would try to upgrade the driver and try again.
